name: my_conda_env
dependencies:
  - python=3.12
  - gcc=11.2.0
  - gxx=11.2.0
  - numpy
  - scipy
  - pip
  - pip:
      - prefect
      - cloudpickle
      - uv
      - qcsc-prefect
      - prefect-qiskit