#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Initialize examples/prefect_bitcount_demo/bitcount_blocks.toml.

Usage:
  ./scripts/init_bitcount_config.sh --target miyabi --project PROJECT --queue QUEUE --work-dir WORK_DIR [options]
  ./scripts/init_bitcount_config.sh --target fugaku --group GROUP --queue QUEUE --work-dir WORK_DIR [options]

Options:
  --target miyabi|fugaku        HPC target for the BitCount tutorial
  --project PROJECT             Miyabi project name, such as gz00
  --group GROUP                 Fugaku group name, such as ra000000
  --queue QUEUE                 Miyabi queue or Fugaku rscgrp
  --work-dir WORK_DIR           Base work directory for BitCount runs
  --optimized-executable PATH   Optional absolute path to get_counts_hist
  -h, --help                    Show this help

This script only writes the BitCount block config file. It does not submit HPC
jobs, create Prefect blocks, configure IBM Quantum credentials, or start
Prefect services.
EOF
}

error() {
  printf 'Error: %s\n' "$*" >&2
}

need_value() {
  local option="$1"
  local value="${2:-}"
  if [[ -z "$value" || "$value" == --* ]]; then
    printf 'Missing value for %s\n\n' "$option" >&2
    usage >&2
    exit 2
  fi
}

toml_string() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

TARGET=""
PROJECT=""
GROUP=""
QUEUE=""
WORK_DIR=""
OPTIMIZED_EXECUTABLE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      need_value "$1" "${2:-}"
      TARGET="$2"
      shift 2
      ;;
    --project)
      need_value "$1" "${2:-}"
      PROJECT="$2"
      shift 2
      ;;
    --group)
      need_value "$1" "${2:-}"
      GROUP="$2"
      shift 2
      ;;
    --queue)
      need_value "$1" "${2:-}"
      QUEUE="$2"
      shift 2
      ;;
    --work-dir)
      need_value "$1" "${2:-}"
      WORK_DIR="$2"
      shift 2
      ;;
    --optimized-executable)
      need_value "$1" "${2:-}"
      OPTIMIZED_EXECUTABLE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ ! -f "mkdocs.yml" || ! -d "examples/prefect_bitcount_demo" ]]; then
  error "run this script from the qcsc-prefect repository root"
  exit 1
fi

case "$TARGET" in
  miyabi)
    if [[ -z "$PROJECT" ]]; then
      error "--project is required when --target miyabi"
      exit 2
    fi
    EXECUTION_PROFILE_BLOCK_NAME="exec-bitcount-mpi"
    HPC_PROFILE_BLOCK_NAME="hpc-miyabi-bitcount"
    OPTIONS_VARIABLE_NAME="miyabi-bitcount-options"
    ;;
  fugaku)
    if [[ -z "$GROUP" ]]; then
      error "--group is required when --target fugaku"
      exit 2
    fi
    EXECUTION_PROFILE_BLOCK_NAME="exec-bitcount-fugaku"
    HPC_PROFILE_BLOCK_NAME="hpc-fugaku-bitcount"
    OPTIONS_VARIABLE_NAME="fugaku-bitcount-options"
    ;;
  "")
    error "--target is required"
    exit 2
    ;;
  *)
    error "--target must be either 'miyabi' or 'fugaku'"
    exit 2
    ;;
esac

if [[ -z "$QUEUE" ]]; then
  error "--queue is required"
  exit 2
fi

if [[ -z "$WORK_DIR" ]]; then
  error "--work-dir is required"
  exit 2
fi

CONFIG_PATH="examples/prefect_bitcount_demo/bitcount_blocks.toml"
TEMP_PATH="${CONFIG_PATH}.tmp"

{
  printf '# Generated by scripts/init_bitcount_config.sh\n'
  printf '# Rerun the script to update this file.\n\n'
  printf 'hpc_target = %s\n' "$(toml_string "$TARGET")"
  if [[ "$TARGET" == "miyabi" ]]; then
    printf 'project = %s\n' "$(toml_string "$PROJECT")"
  else
    printf 'group = %s\n' "$(toml_string "$GROUP")"
  fi
  printf 'queue = %s\n' "$(toml_string "$QUEUE")"
  printf 'work_dir = %s\n\n' "$(toml_string "$WORK_DIR")"
  if [[ -n "$OPTIMIZED_EXECUTABLE" ]]; then
    printf 'optimized_executable = %s\n\n' "$(toml_string "$OPTIMIZED_EXECUTABLE")"
  fi
  printf 'command_block_name = "cmd-bitcount-hist"\n'
  printf 'execution_profile_block_name = %s\n' "$(toml_string "$EXECUTION_PROFILE_BLOCK_NAME")"
  printf 'hpc_profile_block_name = %s\n' "$(toml_string "$HPC_PROFILE_BLOCK_NAME")"
  printf 'options_variable_name = %s\n' "$(toml_string "$OPTIONS_VARIABLE_NAME")"
} >"$TEMP_PATH"

mv "$TEMP_PATH" "$CONFIG_PATH"

printf 'Wrote %s\n\n' "$CONFIG_PATH"
printf 'Next command:\n'
printf '  python examples/prefect_bitcount_demo/create_blocks.py \\\n'
printf '    --config examples/prefect_bitcount_demo/bitcount_blocks.toml \\\n'
printf '    --hpc-target %s\n' "$TARGET"
